### ISSUE TITLE
Review, part 1

### ISSUE THREAD

**Issue by fprochazka** [jprochazk/blog#7]
- `.env` by neměl obsahovat ani hesla localhostu, ani secrets, ani nic... protože když to pak commitneš, každy si to může přečíst na Githubu - přečti si prvních 15 řádků v tom souboru
- misto `sql.txt` by bylo hezčí fixnout migrace
    - v `Version20190222172000` můžeš mít snadno v jedné metodě migraci pro postgre i migraci pro mysql - tu `$this->connection->getDatabasePlatform()->getName()` můžeš použít v podmínce a mit tam sekci pro jednotlive databáze
- `php vendor/bin/phpstan analyze -c 'phpstan.neon' src --level 2`
    - jsi se zaseknul na levelu 2?
- `dg/composer-cleaner` ti maže soubory co potřebuje phpstan
- `favicon.ico` patří do `public/`
- `public/js/admin/showHideButton.js`
    - chybí ti `var` u `id` a `name`
- `BlogController`
    - routuje na `/admin` a řeší něco s AdminFacade, ale jmenuje se Blog
    - proč to `/error` neni v nějakej ErrorControlleru ? 
    - tahle syntax `if(($authenticationError = $this->authFacade->getAuthenticationError()) !== null) {` sice vypadá cool, ale realně to snižuje čitelnost a udržitelnost kodu
- `AuthenticationFacade`
    - to handlovani vyjimek v `saveUser` ... hodně špatny, v realne aplikaci by tě tohle strašně posralo, protože by ses vubec nedozvěděl o tom, že je nějaky problém... pokud nechceš vyjimku handlovat, ale ignorovat, tak minimum co musis udělat je, poslat si tam nějaky logger a zalogovat ji
        - symfony na to použiva monolog, dokonce ho máš nainstalovanej a možná i nakonfigurovanej
    - fasáda by neměla nic vědět o tom, že existuje nějaky http request a že z něj přišel POST a ten jsi zpracoval nějakym formulařem a pak ty data z formuláře chceš dal nějak zpracovavat... a už vubec by to neměla handlovat
        - spravně bys měl mit objekt, ktery nebude nic jineho než hloupa přepravka na data a tento objekt bude fasáda přijimat... a pak v controlleru ošefuješ ten formulář, naplníš z něj ten hloupy objekt a pošleš do fásady, kde už jsou to z pohledu fasády jen nějaka data, se kteryma si uděla co chce - absolutně z toho zmizi jakakoliv informace, že to přišlo přes HTTP přes formulář - fasáda by o tom neměla nic vědět
        - potom ta fasáda může hazet vyjimky, nebo vracet nějaky vysledek, na zakladě ktereho pak zase controller komunikuje s uživatelem - napřiklad že se  nepovedlo ukladani, tak vypišeš nějakou chybu
    - vidim tu ` == null` ... pokud k tomu nemaš duvod (a tady imho žadny neni), vždy použivej porovnani identitou `===`
    - `getAuthenticationError` volaš 2x za sebou `$this->security->getUser()` přitom poprve sis to uložil do proměnné.. jsi mohl použit tu `$user`, ne?
    - `getRegistrationForm`, `getRegistrationFormView`, ... fasáda by neměla řešit formuláře, symfony na to ma definovany jiny mechanismus jak skládat a vyrabět formuláře v controllerech
- `AdminFacade`
    - zase se tu objevuje `Request`, ten tu nema vubec byt
    - je dobry řadit metody v třídě tak, aby když ji procházíš z hora, začneš public metodama a pokud ta metoda potřebuje jine metody na stejne třídy, tak tyto jsou pod ní - aby byla vždy metoda kterou voláš z venku a pak metody ktery se volaji interně
    - dost sis tady zjednodušil praci s těmi daty v administraci - ale to neni vubec hezkej zpusob, takhle to spatlat dohromady
- `Person`
    - to `Serializable` na te entitě neni moc pěkny... zrovna u uživatele, aby jsi ho mohl poslat do session, tak je lepší posilat si tam jenom jeho IDčko a ne celou entitu
        - symfony na to určitě bude mit nějaky interface, ktery si můžeš naimplementovat, ktery řeši aby jsi nemusel serializovat celou tu entitu
        - to `unserialize($string, ['allowed_classes' => false]);` je pruser waiting-to-happen
    - ty votes a surveys jsou dobra prasarna, proč jsi to neudělal jako samostatnou entitu?
- `CommentController`
    - vubec tady neřešiš věci typu, že když zkusíš mazat komentář co neexistuje, nemělo by to vratit 200, ale 404 ... vracet dycky 200 OK ti možná maličko zjednodušuje handlovani v Javascriptu, ale neni to spravně
- `CommentFacade`
    - zase vubec nehandluješ chyby persistence
    - fasády by neměly mít stav - a přihlašenej uživatel je stav, měl bys tam mit pouze bezstavovy služby
        - misto ukladani si `$security->getUser()` by sis měl uložit to `$security` a pak když toho uživatele potřebuješ, tak si ho z te služby vytahnout
    - vubec nehandlujes, co se ma stat, když post nebo komentář neexistuje, ale prostě předpokladaš že existují - bude ti to hazet chyby
        - `http://www.tentato.eu/post/146255555555555555555555555534/comment?showJson=1`
        - `curl -v 'http://www.tentato.eu/post/146234/comment' -H 'Accept: */*' -H 'X-Requested-With: XMLHttpRequest'`
- `Comment`
    - vubec nevyužíváš konstruktory - například to `date` bys měl inicializovat v konstruktoru, stejně tak bys v konstruktoru měl vyžadovat ten post ke kteremu to patří, autora a samotny obsah... a jediny setter na te entitě by pak byl na ten obsah (pokud chceš dovolovat editace)

**Comment by jprochazk** [comment]
snad jsem nic nevynechal
